I_popul = 312032486
print("The Initial population is", end=' ')
print(I_popul)
print(".")
print("\n")
Sec_year = (60*60*24*365)
print("There are", end=' ')
print(Sec_year, end=' ')
print("seconds in a year.")
print("\n")
print("\n")

print("Thus based on the information given,", end=' ')
Births_year  = (Sec_year//7)
print("there are", end=' ')
print(Births_year)
print("births in a year.")
print("\n")
Deaths_year = (Sec_year//13)
print("There are", end=' ')
print(Deaths_year)
print("deaths in a year.")
print("\n")
Immig_year = (Sec_year//45)
print("There are", end=' ')
print(Immig_year)
print("new immigrants in a year.")
print("\n")

Year_one = (I_popul + Births_year - Deaths_year + Immig_year)

Year_two = (Year_one + Births_year - Deaths_year + Immig_year)

Year_three = (Year_two + Births_year - Deaths_year + Immig_year)

Year_four = (Year_three + Births_year - Deaths_year + Immig_year)

Year_five = (Year_four + Births_year - Deaths_year + Immig_year)


print("Every year there are", end=' ')
print(Births_year, end=' ')
print("Births,", end=' ')
print(Deaths_year, end=' ')
print("Deaths, and \n", end='')
print(Immig_year, end=' ')
print("new immigrants enter the counrty.")
print("\n")
print("Based on the information gathered by the National Census Bereau \nthe", end=' ')
print("total population for year one is",end=' ')
print(Year_one, end='')
print(".")
print("The total population for year two is", end=' ')
print(Year_two, end='')
print(".")
print("The total population for year three is", end=' ')
print(Year_three, end='')
print(".")
print("The total population for year four is",end=' ')
print(Year_four, end='')
print(".")
print("The total population for year five is", end=' ')
print(Year_five, end='')
print(".")
